# 日志配置
# 日志文件存放路径 | 默认值：logs （当前目录下的 logs 文件夹）
log_dir = "logs"

# 单个日志文件最大大小（单位：MB）| 默认值：100
max_file_size_mb = 1

# MQTT 话题列表
# 话题中的 / 会自动转为 _ 用于日志文件名
topics = ["subscribe001", "hs/canlog001", "bg/vehicle/state"]

# 设备超时时间（单位：秒）
# 超过此时间没有新消息则认为设备离线，将创建新日志文件
# 默认值：1
timeout_secs = 1

# 日志保留时间（单位：小时）
# 超过此时间的日志文件将被自动清理
# 设置为 0 则不自动清理
# 默认值：0
log_retention_hours = 12

# MQTT 服务器配置
host = "192.168.1.13"
port = 41883
